### PR TITLE
Implements a "general" VC lobby for each series.

### PR DESCRIPTION
**Pull request by blister**
Everyone has started chilling in General VC, but gets hectic when there are multiple series going on. This PR creates a third lobby that members of blue and orange are able to access, but separate from the global General VC.

### CODE REVIEW

**Comment by BenjaminHunt** [comment]
The changes you have look good, but I think its missing a couple items.

The general voice channel should be added to the `to_dict` function, and added to the `pre_load_data` function in the sixMans class. It might be worthwhile to add this as an option/setting.

I can look back at this again in a little bit.

**Comment by blister** [comment]
> The changes you have look good, but I think its missing a couple items.
> 
> The general voice channel should be added to the `to_dict` function, and added to the `pre_load_data` function in the sixMans class. It might be worthwhile to add this as an option/setting.
> 
> I can look back at this again in a little bit.

Thanks for the feedback. I looked around to see if there were other areas I needed to touch but nothing jumped out. I'll go read through the to_dict function and check inside the class pre_load_data area. Thanks again.

**Comment by blister** [comment]
> The changes you have look good, but I think its missing a couple items.
> 
> The general voice channel should be added to the `to_dict` function, and added to the `pre_load_data` function in the sixMans class. It might be worthwhile to add this as an option/setting.
> 
> I can look back at this again in a little bit.

If I'm reading this correctly, the `to_dict` and `_pre_load_data` functions are both pulling info from the game dictionary that is set in game.py on line 100 where we specify `self.voiceChannels = [blue_vc, oran_vc, general_vc]`. Because it's put in self.voiceChannels, `to_dict`, when called, is setting `"VoiceChannels": vc_channels,` which pulls from self.voiceChannels already. 

Then in sixMans.py, `_pre_load_data` seems to be grabbing that same value correctly on line 1590 and pulling the dict from `"VoiceChannels"`. 

Let me know if you spot something I missed, but I _think_ this should work as submitted.

**Comment by blister** [comment]
@BenjaminHunt - have you had a chance to review my comment responses or give the code a thorough look?

**Review by adammast — APPROVED** [review]
Changes look good to me and follow the same format as the existing ones in its creation. I appreciate you looking into the to_dict and pre_load_data functions to see how those work with the voice channels array.

**Comment by BenjaminHunt** [comment]
I suggested he tries to get a test run on his own machine/environment. I would have but it's been a busy past couple weeks.

As long as the `pre_load_data` method was updated as well, this should be all set.

I think it might be worthwhile to add a configuration setting to enable or disable this feature, but that's something we can revisit.

**Comment by BenjaminHunt** [comment]
LGTM

**Comment by BenjaminHunt** [comment]
Might be good to put this behind a feature setting in the future

**Pull request merged**
